config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'chatrooms#show', id: Chatroom.exists? ? Chatroom.first.id : nil
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post "private-chatroom" => "chatrooms#create_private_chatroom"
  resources :chatrooms, only: %i[show create] do
    resources :messages, only: :create
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  validates_uniqueness_of :name
  
  # check if a private chatroom between two users already exists
  def self.find_existing_private_chatroom(user1_id, user2_id)
    Chatroom.joins(chatroom_users: :user)
      .where(is_private: true)
      .where(users: { id: [user1_id, user2_id] })
      .group('chatrooms.id')
      .having('COUNT(chatrooms.id) = 2')
      .first
  end
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages, dependent: :destroy
  has_many :chatroom_users, dependent: :destroy
  has_many :chatrooms, through: :chatroom_users
  validates_uniqueness_of :email, :nickname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @users = User.where.not(id: current_user.id)
    @chatrooms = Chatroom.all
    @chatroom = Chatroom.find(params[:id])
    @new_chatroom = Chatroom.new
    @message = Message.new
    # For displaying the correct chatroom name in the view
    if @chatroom.is_private
      @chatroom_name = @chatroom.users.reject { |user| user == current_user }.first.nickname
    else
      @chatroom_name = @chatroom.name
    end
  end

  def create
    @new_chatroom = Chatroom.new(new_chatroom_params)
    if @new_chatroom.save
      redirect_to chatrooms_path
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  # Chatroom between two users
  def create_private_chatroom
    user = User.find(private_chatroom_params[:user_id])
    user1_id = user.id
    user2_id = current_user.id
    existing_chatroom = Chatroom.find_existing_private_chatroom(user1_id, user2_id)

    if existing_chatroom
      redirect_to existing_chatroom
    else
      new_private_chatroom = Chatroom.new(is_private: true)
      new_private_chatroom.name = "#{user.nickname}/#{current_user.nickname}"

      if new_private_chatroom.save
        add_chatroom_users(new_private_chatroom, user, current_user)
        redirect_to new_private_chatroom
      else
        render "chatrooms/show", status: :unprocessable_entity
      end
    end
  end

  private

  def add_chatroom_users(new_private_chatroom, user, current_user)
    ChatroomUser.create(user: user, chatroom: new_private_chatroom)
    ChatroomUser.create(user: current_user, chatroom: new_private_chatroom)
  end

  def private_chatroom_params
    params.require(:chatroom).permit(:user_id)
  end

  def new_chatroom_params
    params.require(:chatroom).permit(:name)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: {message: @message})
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/show.html.erb
<div class="d-flex container">
  <div class="container chatroom" data-controller="chatroom-subscription"
    data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">
    <h1><%= @chatroom_name %></h1>

    <div class="messages" data-chatroom-subscription-target="messages" >
      <% @chatroom.messages.each do |message| %>
        <%= render 'messages/message', message: message %>
      <% end %>
    </div>
    <%= simple_form_for [@chatroom, @message],
      html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" },
      class: "d-flex" } do |f| %>
      <%= f.input :content,
        label: false,
        wrapper_html: {class: "flex-grow-1"}
      %>
      <%= f.submit "Send", class: "btn btn-primary mb-3" %>
    <% end %>
  </div>

  <div class="d-flex flex-column mt-2 flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <h3>Chatrooms:</h3>
    <ul class="nav nav-pills flex-column mb-auto">
      <% @chatrooms.reject{ |chatroom| chatroom.is_private }.each do |chatroom| %>
        <li class="nav-item">
          <%= link_to chatroom.name, chatroom_path(chatroom), class: "nav-link"  %>
        </li>
      <% end %>
    </ul>
    <h3>Users:</h3>
    <ul class="nav nav-pills flex-column mb-auto">
      <% @users.each do |user| %>
        <li class="nav-item">
          <%= button_to user.nickname, private_chatroom_path, method: :post, params: { chatroom: {user_id: user.id} }, class: "nav-link"  %>
        </li>
      <% end %>
    </ul>
    <hr>
    <h2>New chatroom</h2>
    <%= simple_form_for @new_chatroom, class: "d-flex" do |f| %>
      <%= f.input :name,
        label: false,
        placeholder: "Chatroom name",
        wrapper_html: {class: "flex-grow-1"}
      %>
      <%= f.submit "Create", class: "btn btn-primary mb-3" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiveChat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.nickname %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid justify-content-end">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" data-bs-toggle="dropdown"><%= current_user.nickname %>  <i class="fa-solid fa-chevron-down"></i></a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>